[project]
name = "news-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.14.0",
    "pykrx>=1.0.51",
    "requests>=2.32.5",
    "telegram>=0.0.1",
]
